const express=require("express")
const router=express.Router()
const {allData,login,register,addBook, getUserBooks}=require("../controller/controller.js")
const {authUser}=require("../middleware/authUser.js")
router.get("/all",allData)
router.post("/login",login)
router.post("/register",register)
router.post("/addbook",addBook)
router.get("/books",getUserBooks)
module.exports=router