const express=require("express")
const router=express.Router()
const {allData,login,register,addBook, getUserBooks, logout, deleteBook}=require("../controller/controller.js")
const {authUser}=require("../middleware/authUser.js")
router.get("/all",allData)
router.post("/login",login)
router.post("/register",register)
router.post("/addbook",addBook)
router.post("/logout",logout)
router.get("/books",authUser,getUserBooks)
router.delete("/book/:id",authUser,deleteBook)
module.exports=router