const express=require("express")
const router=express.Router()
const {allData,login,register,addBook, getUserBooks, logout, deleteBook, loginPage}=require("../controller/controller.js")
const {authUser}=require("../middleware/authUser.js")
router.get("/all",authUser,allData)
router.post("/login",login)
router.post("/register",register)
router.post("/addbook",authUser,addBook)
router.post("/logout",logout)
router.get("/books",authUser,getUserBooks)
router.delete("/deletebook",authUser,deleteBook)
router.get("/login",loginPage)
module.exports=router